name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        npx playwright install  # Baixa os navegadores necessários

    - name: Run Playwright tests
      run: npm run test

    - name: Upload Allure report as artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/
        
    - name: Upload Playwright HTML report as artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-html-report
        path: playwright-report/